# Generated by Django 4.1.6 on 2023-02-12 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Person", "0001_initial"),
        ("Event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Person.person"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Person.person"
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("person", "event"), name="unique_person_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("evt_date__gte", datetime.datetime(2023, 2, 12, 17, 4, 7, 826963))
                ),
                name="evt_date_gte_now",
            ),
        ),
    ]
