# Generated by Django 4.1.6 on 2023-02-13 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0003_remove_event_evt_date_gte_now_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event", name="Date doit être superieur au date systeme",
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("evt_date__gte", datetime.datetime(2023, 2, 13, 9, 39, 26, 126733))
                ),
                name="Date doit être superieur au date systeme",
            ),
        ),
    ]
