# Generated by Django 4.1.6 on 2023-02-13 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Event",
            "0004_remove_event_date doit être superieur au date systeme_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event", name="Date doit être superieur au date systeme",
        ),
        migrations.AddField(
            model_name="event",
            name="nbe_participant",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("evt_date__gte", datetime.datetime(2023, 2, 13, 9, 43, 8, 794466))
                ),
                name="Date doit être superieur au date systeme",
            ),
        ),
    ]
