# Generated by Django 4.1.6 on 2023-02-13 08:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "Event",
            "0005_remove_event_date doit être superieur au date systeme_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event", name="Date doit être superieur au date systeme",
        ),
        migrations.AddField(
            model_name="event",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("evt_date__gte", datetime.datetime(2023, 2, 13, 9, 45, 6, 277269))
                ),
                name="Date doit être superieur au date systeme",
            ),
        ),
    ]
