# Generated by Django 4.1.6 on 2023-02-13 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Event",
            "0006_remove_event_date doit être superieur au date systeme_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event", name="Date doit être superieur au date systeme",
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("evt_date__gte", datetime.datetime(2023, 2, 13, 9, 58, 1, 165227))
                ),
                name="Date doit être superieur au date systeme",
            ),
        ),
    ]
