# Generated by Django 4.1.6 on 2023-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Person", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="mail",
            field=models.EmailField(default="mmr@esprit.tn", max_length=254),
            preserve_default=False,
        ),
    ]
